mqtt:
  enabled: true
  host: mosquitto
  port: 1883
  topic_prefix: frigate
  client_id: frigate_nvr
logger:
  default: info
  logs:
    frigate.record: info
    frigate.detectors: info
    frigate.events: info
    frigate.video: info
ffmpeg:
  output_args:
    record: -f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c:v copy -bsf:v h264_redundant_pps -c:a aac
model:
  path: /openvino-model/ssdlite_mobilenet_v2.xml
  width: 300
  height: 300
  input_tensor: nhwc
  input_pixel_format: bgr
  labelmap_path: /openvino-model/coco_91cl_bkgr.txt
detectors:
  ov:
    type: openvino
    device: GPU
    model_path: /openvino-model/ssdlite_mobilenet_v2.xml
    model:
      width: 300
      height: 300
      input_tensor: nhwc
      input_pixel_format: bgr
      path: /openvino-model/ssdlite_mobilenet_v2.xml
motion:
  threshold: 25
  contour_area: 20
  improve_contrast: true
objects:
  track:
  - person
  - car
  - motorcycle
  - bus
  - dog
  - cat
  - bicycle
  filters:
    person:
      min_score: 0.5
      threshold: 0.6
      min_area: 400
    car:
      min_score: 0.65
      threshold: 0.7
      min_area: 1200
    motorcycle:
      min_score: 0.55
      threshold: 0.65
      min_area: 800
    bus:
      min_score: 0.55
      threshold: 0.65
      min_area: 2000
    bicycle:
      min_score: 0.55
      threshold: 0.65
      min_area: 500
    dog:
      min_score: 0.55
      threshold: 0.65
      min_area: 500
    cat:
      min_score: 0.55
      threshold: 0.65
      min_area: 400
snapshots:
  enabled: true
  clean_copy: true
  timestamp: true
  bounding_box: true
  quality: 98
  height: 1080
go2rtc:
  streams:
    cam_192_168_1_189_sub:
    - rtsp://admin:admin@192.168.1.189:554/live/0/SUB#backchannel=0
    cam_192_168_1_189:
    - rtsp://127.0.0.1:8554/cam_192_168_1_189_sub
    cam_192_168_1_189_720p:
    - rtsp://127.0.0.1:8554/cam_192_168_1_189_sub

    cam_192_168_1_196_sub:
    - rtsp://admin:admin@192.168.1.196:554/live/0/SUB#backchannel=0
    cam_192_168_1_196:
    - rtsp://127.0.0.1:8554/cam_192_168_1_196_sub
    cam_192_168_1_196_720p:
    - rtsp://127.0.0.1:8554/cam_192_168_1_196_sub

    cam_192_168_1_200_sub:
    - rtsp://admin:admin@192.168.1.200:554/live/0/SUB#backchannel=0
    cam_192_168_1_200:
    - rtsp://127.0.0.1:8554/cam_192_168_1_200_sub
    cam_192_168_1_200_720p:
    - rtsp://127.0.0.1:8554/cam_192_168_1_200_sub

    cam_192_168_1_93_sub:
    - rtsp://admin:admin@192.168.1.93:554/live/0/SUB#backchannel=0
    cam_192_168_1_93:
    - rtsp://127.0.0.1:8554/cam_192_168_1_93_sub
    cam_192_168_1_93_720p:
    - rtsp://127.0.0.1:8554/cam_192_168_1_93_sub
  webrtc:
    candidates:
    - 100.93.129.91:8555
    - 192.168.1.247:8555
    - stun:8555
    - stun:stun.l.google.com:19302
cameras:
  cam_192_168_1_189:
    enabled: true
    ffmpeg:
      hwaccel_args: preset-intel-qsv-h264
      inputs:
      - path: rtsp://127.0.0.1:8554/cam_192_168_1_189
        input_args: preset-rtsp-restream
        roles:
        - record
        - detect
      output_args:
        record: -f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c:v copy -bsf:v h264_redundant_pps -c:a aac
    detect:
      width: 800
      height: 448
      fps: 5
      enabled: true
    snapshots:
      enabled: true
      bounding_box: true
    objects:
      track:
      - person
      - car
      - motorcycle
      - dog
      filters:
        person:
          threshold: 0.7
    motion:
      threshold: 25
    record:
      enabled: true
      motion:
        days: 14
      continuous:
        days: 0
      alerts:
        pre_capture: 10
        post_capture: 10
        retain:
          days: 14
          mode: active_objects
      detections:
        pre_capture: 10
        post_capture: 10
        retain:
          days: 14
          mode: active_objects
    review:
      alerts:
        labels:
        - person
        - car
        - motorcycle
        - bus
        - dog
        - cat
        - bicycle
        required_zones: []
      detections:
        labels:
        - person
        - car
        - motorcycle
        - bus
        - dog
        - cat
        - bicycle
        required_zones: []

  cam_192_168_1_196:
    enabled: true
    ffmpeg:
      hwaccel_args: preset-intel-qsv-h264
      inputs:
      - path: rtsp://127.0.0.1:8554/cam_192_168_1_196
        input_args: preset-rtsp-restream
        roles:
        - record
        - detect
      output_args:
        record: -f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c:v copy -bsf:v h264_redundant_pps -c:a aac
    detect:
      width: 800
      height: 448
      fps: 5
      enabled: true
    snapshots:
      enabled: true
      bounding_box: true
    objects:
      track:
      - person
      - car
      - motorcycle
      - dog
      filters:
        person:
          threshold: 0.7
    motion:
      threshold: 25
    record:
      enabled: true
      motion:
        days: 14
      continuous:
        days: 0
      alerts:
        pre_capture: 10
        post_capture: 10
        retain:
          days: 14
          mode: active_objects
      detections:
        pre_capture: 10
        post_capture: 10
        retain:
          days: 14
          mode: active_objects
    review:
      alerts:
        labels:
        - person
        - car
        - motorcycle
        - bus
        - dog
        - cat
        - bicycle
        required_zones: []
      detections:
        labels:
        - person
        - car
        - motorcycle
        - bus
        - dog
        - cat
        - bicycle
        required_zones: []

  cam_192_168_1_200:
    enabled: false
    ffmpeg:
      hwaccel_args: preset-intel-qsv-h264
      inputs:
      - path: rtsp://127.0.0.1:8554/cam_192_168_1_200
        input_args: preset-rtsp-restream
        roles:
        - record
        - detect
    detect:
      width: 800
      height: 448
      fps: 5
      enabled: true
    snapshots:
      enabled: true
      bounding_box: true
    objects:
      track:
      - person
      - car
      - motorcycle
      - dog
      filters:
        person:
          threshold: 0.7
    motion:
      threshold: 25
    record:
      enabled: true
      motion:
        days: 14
      continuous:
        days: 0

  cam_192_168_1_93:
    enabled: false
    ffmpeg:
      hwaccel_args: preset-intel-qsv-h264
      inputs:
      - path: rtsp://127.0.0.1:8554/cam_192_168_1_93
        input_args: preset-rtsp-restream
        roles:
        - record
        - detect
    detect:
      width: 800
      height: 448
      fps: 5
      enabled: true
    snapshots:
      enabled: true
      bounding_box: true
    objects:
      track:
      - person
      - car
      - motorcycle
      - dog
      filters:
        person:
          threshold: 0.7
    motion:
      threshold: 25
    record:
      enabled: true
      motion:
        days: 3
      continuous:
        days: 0
version: 0.17-0
