mqtt:
  enabled: true
  host: mosquitto
  port: 1883
  topic_prefix: frigate
  client_id: frigate_nvr

# Hardware Acceleration & Stream Generic Defaults
ffmpeg:
  hwaccel_args: preset-vaapi

detectors:
  ov:
    type: openvino
    device: GPU
    model:
      path: /openvino-model/ssdlite_mobilenet_v2.xml

objects:
  track:
    - person
    - car
    - motorcycle
    - bus
    - truck
    - dog
    - cat

record:
  enabled: true
  retain:
    days: 14
    mode: all
  events:
    pre_capture: 10
    post_capture: 15
    retain:
      default: 30
      mode: motion

snapshots:
  enabled: true
  clean_copy: true
  timestamp: true
  bounding_box: true

# go2rtc WebRTC Hub
go2rtc:
  streams:
    camera_principal:
      - rtsp://192.168.1.6:8554/stream#transport=tcp
      - "ffmpeg:camera_principal#video=h264"
  webrtc:
    listen: ":8555"
    candidates:
      - 127.0.0.1:8555
      - stun:8555

# Câmera Principal
cameras:
  camera_principal:
    ffmpeg:
      inputs:
        - path: rtsp://192.168.1.6:8554/stream
          input_args: preset-rtsp-generic
          roles:
            - detect
            - record
    detect:
      enabled: true
      fps: 5
    zones:
      zona_monitoramento:
        coordinates: 0,720,1280,720,1280,100,0,100
        objects:
          - person
          - car
          - motorcycle
